version: "3.7"

services:
  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=traffic_pulse_db
      - PGPORT=5431
    ports:
      - 5431:5431
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  data_downloader:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.data_downloader
    container_name: data_downloader
    depends_on:
      db:
        condition: service_healthy
    restart: always
    links:
      - db
    environment:
      - DB_CONN_STR=postgresql+psycopg2://postgres:postgres@db:5431/traffic_pulse_db

volumes:
  postgres-data:
    driver: local
