apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/traffic-pulse/my-image:v0.1.17
        ports:
        - containerPort: 8080
        env:
          - name: DB_CONN_STR
            value: "postgresql+psycopg2://postgres:postgres@10.59.16.3:5432/traffic-pulse-database"
