FROM python:3.9

WORKDIR /usr/app

COPY ./requirements.txt ./
RUN pip3 install -r requirements.txt

COPY ./data_downloader.py ./orm.py ./alembic.ini ./utils.py ./
ADD db-schemas ./db-schemas

ENTRYPOINT ["python", "data_downloader.py"]
